version: '2'
services:
  ssr-client:
    container_name: ssr-client
    image: hooyao/ss-libev:ssr
    volumes:
      - ./client.json:/root/config/config.json
    entrypoint: ss-redir
    command: -c /root/config/config.json -u
    ports:
      - "1081:1080"